# Generated by Django 3.2.4 on 2021-09-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='updated date')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Songs', to='accounts.songs')),
            ],
        ),
    ]
