import { RootState } from "./store";
export declare const loaded: import("@reduxjs/toolkit").ActionCreatorWithOptionalPayload<boolean, string>, showedChat: import("@reduxjs/toolkit").ActionCreatorWithOptionalPayload<boolean, string>, showedPasteUrl: import("@reduxjs/toolkit").ActionCreatorWithOptionalPayload<boolean, string>, showedModal: import("@reduxjs/toolkit").ActionCreatorWithOptionalPayload<boolean, string>, exitedModal: import("@reduxjs/toolkit").ActionCreatorWithOptionalPayload<boolean, string>, showedMemberList: import("@reduxjs/toolkit").ActionCreatorWithOptionalPayload<boolean, string>, showedDeleteModal: import("@reduxjs/toolkit").ActionCreatorWithOptionalPayload<boolean, string>, setEnterModal: import("@reduxjs/toolkit").ActionCreatorWithOptionalPayload<boolean, string>;
export declare const selectShowChat: (state: RootState) => boolean;
export declare const selectShowPasteUrl: (state: RootState) => boolean;
export declare const selectIsLoading: (state: RootState) => boolean;
export declare const selectShowModal: (state: RootState) => boolean;
export declare const selectShowExitModal: (state: RootState) => boolean;
export declare const selectShowMemberList: (state: RootState) => boolean;
export declare const selectShowDeleteModal: (state: RootState) => boolean;
export declare const selectEnterModal: (state: RootState) => boolean;
declare const _default: import("redux").Reducer<{
    isLoading: boolean;
    showChat: boolean;
    showPasteUrl: boolean;
    showModal: boolean;
    exitModal: boolean;
    showMemberList: boolean;
    showDeleteModal: boolean;
    enterModal: boolean;
}, import("redux").AnyAction>;
export default _default;
